wrap_comments = true
format_strings = true
error_on_unformatted = false
reorder_impl_items = true

condense_wildcard_suffixes = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_macro_bodies = true
#merge_imports = true
normalize_doc_attributes = true
use_field_init_shorthand = true
use_try_shorthand = true